[package]
name = "hcctl"
version = "1.0.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>", "Iain Earl <iain@itmecho.com>"]
edition = "2018"
description = "Command-line tool for interacting with a https://healthchecks.io account"
repository = "https://github.com/msfjarvis/healthchecks-rs"
homepage = "https://github.com/msfjarvis/healthchecks-rs"
license = "MIT/Apache-2.0"
keywords = ["healthchecks"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "3.0.0-beta.4"
color-eyre = { version = "0.5.11", default-features = false }
healthchecks = { path = "../healthchecks", version = "^2.0.0"}
prettytable-rs = "0.8.0"
