[package]
name = "hcctl"
version = "0.1.0"
authors = ["Iain Earl <iain@itmecho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
healthchecks = { path = "../healthchecks", version = "^1.0.2-alpha.0"}
anyhow = "1.0.32"
clap = { version = "2.33.3", default-features = false, features = ["suggestions", "color"] }
prettytable-rs = "0.8.0"
chrono = "0.4.19"
