[package]
name = "hcctl"
version = "0.1.0"
authors = ["Iain Earl <iain@itmecho.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
chrono = "0.4.19"
clap = { version = "3.0.0-beta.2", default-features = false, features = ["std", "suggestions", "color"] }
healthchecks = { path = "../healthchecks", version = "^1.0.2-alpha.0"}
prettytable-rs = "0.8.0"
